log : alog_test.cc ../AsyncLogging.cc ../LogFile.cc ../LogStream.cc ../Thread.cc ../Logging.cc ../TimeStamp.cc 
	g++ alog_test.cc ../AsyncLogging.cc ../LogFile.cc ../LogStream.cc ../Thread.cc ../Logging.cc ../TimeStamp.cc -o l.out -lpthread

front : ./loger_test.cc  ../LogStream.cc ../Logging.cc ../TimeStamp.cc 
	g++ ./loger_test.cc ../LogStream.cc ../Logging.cc ../TimeStamp.cc -o logger.out 


clean : 
	rm log.log.2021*
	rm 1
